function exists() {
    command -v $1 >/dev/null
}


export PATH="/opt/homebrew/opt/libpq/bin:$PATH"
# export PATH=$PATH:/Users/lewismcneill/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/solargraph-0.50.0/lib/solargraph.rb
# export PATH=$PATH:/Users/lewismcneill/dev/test/terravision


. "$HOME/.cargo/env"
